name: Compilar OpenWrt CSI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Compilar en Ubuntu 18.04 (Docker)
      run: |
        docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace ubuntu:18.04 /bin/bash -c "
          apt-get update && 
          DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential git libncurses5-dev zlib1g-dev gawk flex quilt libssl-dev unzip python time file wget curl sudo bison gettext autoconf automake libtool pkg-config bc m4 &&
          git clone https://github.com/xieyaxiongfly/Atheros_CSI_tool_OpenWRT_src.git openwrt &&
          cd openwrt &&
          ./scripts/feeds update -a &&
          ./scripts/feeds install -a &&
          cp ../config_wr720n.txt .config &&
          make defconfig &&
          FORCE_UNSAFE_CONFIGURE=1 FORCE=1 make -j\$(nproc) V=s
        "
    - name: Subir archivo BIN
      uses: actions/upload-artifact@v4
      with:
        name: WR720N-CSI-Firmware
        path: openwrt/bin/ar71xx/*.bin
